packages:
    # packages/ 直接子目录中的所有包
    - packages/*
    - play-v2
    - play-v3

catalogs:
    vue3:
        vue: 3.5.14
        rollup-plugin-vue: 6.0.0
    vue2.6:
        vue: 2.6.14
        vue-template-compiler: 2.6.14
        rollup-plugin-vue: 5.1.9
